services:
  order:
    build: ./orderService
    ports:
      - "12340:8000"
  user:
    build: ./userService
    ports:
      - "12341:8000"
  loyalty:
    build: ./loyaltyService
    ports:
      - "12342:8000"
  menu:
    build: ./menuService
    ports:
      - "12343:8000"
  reservation:
    build: ./reservationService
    ports:
      - "12344:8000"
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"